### ISSUE TITLE
Is there RGBA support?

### ISSUE THREAD

**Issue by daviedR** [mexitek/phpColors#15]
Hi @mexitek,

Thanks for this handy class. I was wondering if this class also supports rgba format and some functions for manpulating it. e.g. changeOpacity(). It would be great if these features could be added into your class.

Thanks!

**Comment by lmartins** [comment]
I was also looking into ways of generating colors with transparency, either with RGBA or preferably HSLA but when I try the method `getRgbaCss()`I get:
```
[29-Jan-2015 09:51:40 UTC] PHP Fatal error:  Call to undefined method Mexitek\PHPColors\Color::getRgbaCss()
```

**Comment by mexitek** [comment]
`getRgbaCss()` was a suggested implementation of what @daviedR was wanting. What type of transparency are you looking for? e.g. color on one side of gradient and transparent on the other side of gradient

**Comment by lmartins** [comment]
ops, I missread it then.
My use case would be simpler, I just need to output a color in HSLA or RGBA format so that it could have a transparency value.

**Comment by mexitek** [comment]
if you want the color class to output the css for you then yes this is something that can be added to the class. In reality it sounds like you have ColorA, you use the class to lighten/darken this color resulting in ColorB. Then you want to set an opacity/transparency on ColorB. If that is correct, then you can do that today without giving the class your opacity value.

Let me know if I am not understanding your use case. Otherwise, you might be able to do something like this:
```
// Original Color: 336699
$colorA = new Color("#336699");

// New Color: 1A334D
$colorB = new Color( $colorA->darken() );
$colorBHSL = $colorB->getHsl();

// Your opacity
$opacity = 0.5;

$hslaCss = "hsla(".$colorBHSL['H'].", ".($colorBHSL['S']*100)."%, ".($colorBHSL['L']*100)."%, $opacity)";
```

**Comment by lmartins** [comment]
Nice. A bit laborious if you need to use more than one of these but it actually solves my problem. Thanks.

**Comment by mexitek** [comment]
It is, but the class was meant for manipulating 1 color and producing a
slight gradient. In the process it translates the color into hex, rbg and
hsl for you. I stopped supporting the color class, but I do accept pull
requests. If the community feels the class should expand then I am open to
accepting the code changes.

For your use case, you can abstract the laborious code into a method or a
subclass of color.

On Thu, Jan 29, 2015 at 11:31 AM, Luis Martins <notifications@github.com>
wrote:

> Nice. A bit laborious if you need to use more than one of these but it
> actually solves my problem. Thanks.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mexitek/phpColors/issues/15#issuecomment-72088313>.
>



-- 
Arlo Carreon <http://arlocarreon.com>
Web Developer
