### ISSUE TITLE
Version update

### ISSUE THREAD

**Issue by unzeitigm** [mexitek/phpColors#41]
Hi there, 

would you mind to release next version of this package please, so we can use a version constraint in our `composer.json` files.

Thank you very much, have a nice day.

**Comment by jshah4517** [comment]
Would like to bump this, would be great to lock to a specific version instead of dev-master!

**Comment by peter279k** [comment]
It seems to be great idea to release a stable version rather than using unstable `dev-master` version on other production project.

**Comment by peter279k** [comment]
Version has been updated :+1:.

Closed.
