### ISSUE TITLE
Incorrect conversion from HEX to RGB

### ISSUE THREAD

**Issue by strarsis** [mexitek/phpColors#43]
A yellow color `rgb(244, 231, 15)` is not converted correctly to HEX value.
`#f4e70f` is the correct HEX value, but it is converted to `#f4e7f` instead.
What is noticeable is that again zeroes (`0`) are involved, 
not at the beginning or end of the HEX value string but in between.

**Comment by peter279k** [comment]
The zero should be filled after using `dechex` function to convert the decimal value to hex value.

For example, consider following PHP code snippets:

```PHP
 dechex(15) // output: "f", but it's expected to be "0f"
```

**Comment by peter279k** [comment]
After looking at the `Color.php`, I think it has been fixed.

I use following code snippets to prove this:

```PHP
use Mexitek\PHPColors\Color;

Color::rgbToHex(['R' => 244, 'G' => 231, 'B' => 15]); // "f4e70f"

```

@strarsis, could you provide any sample code about this? Thanks.

**Comment by peter279k** [comment]
@strarsis, I will close this issue.

If having any further issue, please feel free to create/write comment again :).
