### ISSUE TITLE
add tag to commit 9d7cf28aab475a26b9f5be4f9dc4106736956678

### ISSUE THREAD

**Issue by mikashharia** [mexitek/phpColors#49]
Hi,

Is it possible to add a tag to this version so I can fix my composer file with a tag please.

**Comment by peter279k** [comment]
Hi @mikashharia, thanks for your reply.

It doesn't release any version for about whiles....

Do you mind releasing the `1.0` to including from fc9e466c193fd3146678a65215afa4b41f2e9272`to ffdf20bc075da2e495e1bc9ec723547f9bd02694?

**Comment by bytestream** [comment]
https://github.com/mexitek/phpColors/commit/ffdf20bc075da2e495e1bc9ec723547f9bd02694 contains breaking changes

Ideal solution is to tag:
* `0.5` - 9d7cf28aab475a26b9f5be4f9dc4106736956678 
* `1.0` - https://github.com/mexitek/phpColors/commit/ffdf20bc075da2e495e1bc9ec723547f9bd02694

**Comment by mikashharia** [comment]
> [ffdf20b](https://github.com/mexitek/phpColors/commit/ffdf20bc075da2e495e1bc9ec723547f9bd02694) contains breaking changes
> 
> Ideal solution is to tag:
> 
> * `0.5` - [9d7cf28](https://github.com/mexitek/phpColors/commit/9d7cf28aab475a26b9f5be4f9dc4106736956678)
> * `1.0` - [ffdf20b](https://github.com/mexitek/phpColors/commit/ffdf20bc075da2e495e1bc9ec723547f9bd02694)

agreed with this approch

**Comment by peter279k** [comment]
Thanks. I will do these tag versions :).

**Comment by bytestream** [comment]
Thanks man :) please to see someone has picked up the lib!

**Comment by mikashharia** [comment]
Thank you

**Comment by peter279k** [comment]
Hi @bytestream and @mikashharia.

- 0.5 - 9d7cf28
- 1.0 - ffdf20b

These above versions are released. Please use them.

If having any issues, please feel free to create another issue :+1: .
