### ISSUE TITLE
Error in importing Color.php

### ISSUE THREAD

**Issue by tekken3vish** [mexitek/phpColors#54]
This is the error I am getting, using the Color.php 

require_once __DIR__ . '/../PHPColors/Color.php';
This is the only thing I am using, in my php file.

<br />
  | <b>Parse error</b>:  syntax error, unexpected 'const' (T_CONST), expecting variable (T_VARIABLE) in <b>/home/username/public_html/PHPColors/Color.php</b> on line <b>38</b><br />

**Comment by peter279k** [comment]
Hi, thanks for your reply.

Which PHP version do you use?

And which package version do you use?

**Comment by tekken3vish** [comment]
> Hi, thanks for your reply.
> 
> Which PHP version do you use?
> 
> And which package version do you use?

Hi! Thanks for replying, in local host it is working fine, but in hosted server it is not working.

On localhost & hosting ser PHP ver 7.0

**Comment by tekken3vish** [comment]
Thanks for pointing me in the wrong direction, updated the version to the latest, fixed the issue # # #
